export type DocsPublicRoute = {
  path: string;
  file: string;
  priority: string;
  changefreq: string;
};

export const DOCS_PUBLIC_ROUTES = [
  {
    path: '/',
    file: '(home).page.ts',
    priority: '1.0',
    changefreq: 'weekly',
  },
  {
    path: '/docs/introduction',
    file: 'docs/introduction.page.ts',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/docs/installation',
    file: 'docs/installation.page.ts',
    priority: '0.9',
    changefreq: 'weekly',
  },
  {
    path: '/docs/inspired-designs',
    file: 'docs/inspired-designs.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/docs/faq',
    file: 'docs/faq.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/composition/overview',
    file: 'composition/overview.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/composition/surface-and-section',
    file: 'composition/surface-and-section.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/composition/stack-and-cluster',
    file: 'composition/stack-and-cluster.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/composition/split-layouts',
    file: 'composition/split-layouts.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/composition/common-patterns',
    file: 'composition/common-patterns.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/button',
    file: 'components/button.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/card',
    file: 'components/card.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/dialog',
    file: 'components/dialog.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/accordion',
    file: 'components/accordion.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/input',
    file: 'components/input.page.ts',
    priority: '0.8',
    changefreq: 'weekly',
  },
  {
    path: '/components/input-group',
    file: 'components/input-group.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/avatar',
    file: 'components/avatar.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/avatar-group',
    file: 'components/avatar-group.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/badge',
    file: 'components/badge.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/callout',
    file: 'components/callout.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/checkbox',
    file: 'components/checkbox.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/chip',
    file: 'components/chip.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/cluster',
    file: 'components/cluster.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/display',
    file: 'components/display.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/halftone',
    file: 'components/halftone.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/icon',
    file: 'components/icon.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/icon-button',
    file: 'components/icon-button.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/image-card',
    file: 'components/image-card.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/label',
    file: 'components/label.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/marquee',
    file: 'components/marquee.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/media-frame',
    file: 'components/media-frame.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/media-item',
    file: 'components/media-item.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/progress',
    file: 'components/progress.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/rating',
    file: 'components/rating.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/select',
    file: 'components/select.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/separator',
    file: 'components/separator.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/section',
    file: 'components/section.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/split',
    file: 'components/split.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/stack',
    file: 'components/stack.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/stat',
    file: 'components/stat.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/status-dot',
    file: 'components/status-dot.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/sticker',
    file: 'components/sticker.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/surface',
    file: 'components/surface.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/text',
    file: 'components/text.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/textarea',
    file: 'components/textarea.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/components/title',
    file: 'components/title.page.ts',
    priority: '0.7',
    changefreq: 'weekly',
  },
  {
    path: '/recipes/travel-card',
    file: 'recipes/travel-card/index.page.ts',
    priority: '0.6',
    changefreq: 'monthly',
  },
  {
    path: '/recipes/podcast-card',
    file: 'recipes/podcast-card/index.page.ts',
    priority: '0.6',
    changefreq: 'monthly',
  },
  {
    path: '/recipes/open-to-work-card',
    file: 'recipes/open-to-work-card/index.page.ts',
    priority: '0.6',
    changefreq: 'monthly',
  },
  {
    path: '/showcase/portfolio',
    file: 'showcase/portfolio/index.page.ts',
    priority: '0.6',
    changefreq: 'monthly',
  },
] as const satisfies readonly DocsPublicRoute[];
