export type NbComponentStatus = 'stable' | 'preview';

export const docsComponentStatus: Readonly<Record<string, NbComponentStatus>> =
  {
    accordion: 'stable',
    avatar: 'stable',
    'avatar-group': 'stable',
    badge: 'stable',
    button: 'stable',
    callout: 'stable',
    card: 'stable',
    checkbox: 'stable',
    chip: 'stable',
    cluster: 'stable',
    dialog: 'stable',
    display: 'stable',
    halftone: 'stable',
    icon: 'stable',
    'icon-button': 'stable',
    'image-card': 'stable',
    input: 'stable',
    'input-group': 'stable',
    label: 'stable',
    marquee: 'preview',
    'media-frame': 'stable',
    'media-item': 'stable',
    progress: 'stable',
    rating: 'stable',
    section: 'stable',
    select: 'preview',
    separator: 'stable',
    split: 'stable',
    stack: 'stable',
    stat: 'stable',
    'status-dot': 'stable',
    sticker: 'stable',
    surface: 'stable',
    text: 'stable',
    textarea: 'stable',
    title: 'stable',
  };
